name: workforce-solution

on:
    from datetime import datetime
    import pandas as pd
    from arcgis.gis import workforce
    import arcgis
    from IPython.display import display
    gis = GIS("pro", verify_cert=False)
    item = gis.content.get("2b1f160772634451b9fb088444fef3f3")
    project = arcgis.apps.workforce.Project(item)
    layer = gis.content.get("c075a748052b4360986978c04bfd2e1d")
    from arcgis.geocoding import geocode
    assignments = []
    layer_item = layer.layers[0].query().sdf
    project_assignments = []
    for feature in layer.layers[0].query():
        assignments.append(
            workforce.Assignment(
                project,    
                geometry=feature.geometry,
                location=feature.attributes["serviceaddress"],
                description=feature.attributes["comments"],
                priority=2,
                assignment_type="Work Order",
                status="unassigned"))
    project.assignments.batch_add(assignments)

env:
    ENVIRONMENT_URL: 
    USERNAME: 
